spring.application.name=Recoomendation-Engine
# Spring AI (OpenAI) Configuration
# Gemini API configuration
spring.ai.vertexai.gemini.project-id=plant-disease-detection-382112
spring.ai.vertexai.gemini.location=us-central1
spring.ai.vertexai.gemini.api-key=AIzaSyD_nOnzWQZXTIgCEc0_zQgBhVBuIa3j3Rg
# MongoDB Configuration (if you haven't already)
#spring.data.mongodb.uri=mongodb://localhost:27017/roadtripplanner
#spring.data.mongodb.database=roadtripplanner

# Server Configuration
server.port=8082
logging.level.org.springframework.boot.autoconfigure=DEBUG
logging.level.org.springframework.ai=DEBUG
logging.level.org.springframework.cloud.gcp=DEBUG