spring.application.name=attraction-Service
server.port=8083
spring.data.mongodb.uri=mongodb://localhost:27017/attraction_db
jwt.secret=a2FqZGtmamFzZGZramxhc2RmamtqczEyMzQ1Njc4OTAxMjM0NTY3OA=
jwt.expiration=3600