spring.application.name=Route-Optimizer
google.maps.api.key=AIzaSyCCJQ5CljwkY-eIbM805m2ndzhExttsuhw
server.port=8080
#logging.level.root=DEBUG
# MongoDB Configuration (if you haven't already)
spring.data.mongodb.uri=mongodb://localhost:27017/roadtripplanner
spring.data.mongodb.database=roadtripplanner
